language: generic

sudo: required

services:
  - docker
 
# image build
script:
  - docker build -t 2donny/docker-backend ./backend
  - docker build -t 2donny/docker-nginx ./nginx
  - docker build -t 2donny/docker-postgres

# Login docker hub
after_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push 2donny/docker-backend
  - docker push 2donny/docker-nginx
  - docker push 2donny/docker-postgres


deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: "docker-backend-app"
  env: "Dockerbackendapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-471011865482
  bucket_path: "docker-backend-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY