version: "3"

services:
  nginx:
    restart: always
    container_name: app_nginx
    image: 2donny/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - backend
    depends_on:
      - backend

  backend:
    image: 2donny/docker-backend
    container_name: "app_backend"
    env_file: .postgres.env
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m

  db:
    image: postgres
    container_name: "app_database"
    ports:
      - "5432:5432"
    env_file: .postgres.env
    mem_limit: 256m
