version: "3"

services:
  nginx:
    restart: "always"
    container_name: "app_nginx"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: "app_backend"
    volumes:
      - /app/node_modules
      - ./backend:/app

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    container_name: "app_database"
